name = "study_topics"
uuid = "edbac871-f2da-447c-81a8-c3741a82c596"
authors = ["mendzmartin <chmartinmendez@gmail.com>"]
version = "0.1.0"

[deps]
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
